---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-release
  namespace: longhorn-system
  annotations:
    kustomize.toolkit.fluxcd.io/depends-on: |
      - group: apps
        kind: Deployment
        name: kube-vip-cloud-provider
spec:
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn-repo
      version: v1.7.2
  interval: 1m0s
