---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
  annotations:
    kustomize.toolkit.fluxcd.io/depends-on: |
      - group: apps
        kind: Deployment
        name: kube-vip-cloud-provider
spec:
  chart:
    spec:
      chart: cert-manager
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cert-manager-repo
      version: 1.16.2
  interval: 1m0s
  releaseName: cert-manager
  targetNamespace: cert-manager
  values:
    crds:
      enabled: true
    extraArgs:
    - --dns01-recursive-nameservers-only
    - --dns01-recursive-nameservers=1.1.1.1:53,9.9.9.9:53
