---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community-repo
  namespace: monitoring
spec:
  interval: 1m0s
  url: https://prometheus-community.github.io/helm-charts
